global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'local-metrics'
    static_configs:
      - targets: ['127.0.0.1:8080'] # Use 'localhost:8080' if Prometheus and the metrics source are on the same machine without Docker.